name: sentibites
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0
  http: ^0.13.4
  intl: ^0.18.0
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cropped_image.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cropped_image.png"
